[package]
name = "ferro-core"
version.workspace = true
edition.workspace = true

[dependencies]
dirs = "6.0.0"
keyring = "4.2.0"
mail-parser = { version = "0.11.8", default-features = false, features = ["full_encoding"] }
native-tls = "0.2.18"
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
tantivy = "0.26.1"
thiserror = "2.0.20"
toml = "1.1.5"

[dev-dependencies]
tempfile = "3.27.0"
